import { useEffect, useId, useRef, useState } from 'react';
import { Icon } from '../Icon';
import { promptReferences, referenceQuery, removePromptReference, type PromptReference } from '../../../shared/prompt-references';

export function PromptBar({ text, setText, search }: { text: string; setText: (text: string) => void; search(query: string): Promise<PromptReference[]> }) {
  const query = referenceQuery(text), [options, setOptions] = useState<PromptReference[]>([]), generation = useRef(0), listId = useId();
  useEffect(() => { if (query === null) { setOptions([]); return; } const current = ++generation.current; void search(query).then(result => { if (current === generation.current) setOptions(result); }).catch(() => { if (current === generation.current) setOptions([]); }); }, [query, search]);
  const refs = promptReferences(text);
  const choose = (path: string) => { const replaced = text.replace(/(^|\s)@[A-Za-z0-9_./-]*$/, `$1@${path} `); setText(replaced); setOptions([]); };
  return <>{refs.length ? <div className="flex flex-wrap gap-1.5 px-2 pb-1" aria-label="已引用上下文">{refs.map(reference => <span key={reference.path} className="prompt-reference inline-flex max-w-full items-center gap-1 rounded-full bg-surface-3 px-2 py-1 text-[11px] text-muted"><Icon name={reference.path === 'Canvas' ? 'panelLeft' : 'chevronRight'} className="size-3 shrink-0" /><span className="truncate">{reference.label}</span><button type="button" aria-label={`移除引用 ${reference.label}`} className="interactive grid size-4 shrink-0 place-items-center rounded-full hover:bg-surface-4 hover:text-hover-fg" onClick={() => setText(removePromptReference(text, reference.path))}><Icon name="x" className="size-2.5" /></button></span>)}</div> : null}{options.length && query !== null ? <div id={listId} role="listbox" aria-label="引用文件" className="prompt-reference-list absolute bottom-full left-2 right-2 z-popover mb-2 max-h-52 overflow-y-auto rounded-xl border border-contrast bg-surface p-1 shadow-lg">{options.map(option => <button key={option.path} type="button" role="option" onMouseDown={event => event.preventDefault()} onClick={() => choose(option.path)} className="interactive flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-xs text-muted hover:bg-surface-3 hover:text-hover-fg"><Icon name={option.path === 'Canvas' ? 'panelLeft' : 'chevronRight'} className="size-3.5 shrink-0" /><span className="truncate">{option.label}</span></button>)}</div> : null}</>;
}
